### ISSUE TITLE
How can i remove element from the list if it is not found withClassLinker?

### ISSUE THREAD

**Issue by hk4774** [drakeet/MultiType#201]
```
.withClassLinker(test -> {
                    switch (some condition from test) {
                        case test.data:
                            return Test1.class;
                        case test.data2:
                            return Test2.class;
                        default:
                            // rather returning something...delete the element from the arraylist.
                       }
}
```

**Comment by drakeet** [comment]
You can not do that. If you can judge that you are going to delete it, why do not you check when add it to your items?

If you just want to hide it, you can provide an ItemViewBinder with Object bound and return it as the default. You can set this binder height to 0 so that it is not visible.

But this is not recommended, the best practice is to throw an exception, because you should check when add.

**Comment by drakeet** [comment]
MultiType is just your type distribution framework and it should not change your data.
