### ISSUE TITLE
Headers and footers

### ISSUE THREAD

**Issue by mac229** [drakeet/MultiType#203]
[ Feature Request]

I would like to have automatic support for headers and footers, but  
`onBindViewHolder()` method is final so I cant override it. Of course it would be good, but in this case it is closed for customization.

**Comment by drakeet** [comment]
See #194

**Comment by drakeet** [comment]
The use of final is intended to avoid user-defined destruction of the package and boils down to the problem of being considered MultiType. If you need to override these final methods, you should consider combining rather than inheriting, that is, creating an Adapter that contains a MultiTypeAdapter instead of inheriting the MultiTypeAdapter.

**Comment by drakeet** [comment]
MultiTypeAdapter is not a class designed for inheritance. The book Effective Java states: Minimize the accessibility of classes and members, and either design for inheritance, provide documentation, or prohibit inheritance. In Kotlin language design, this principle is followed, all classes by default are final, all methods by default are final, unless specifically marked open.

**Comment by mac229** [comment]
Yes, you are right. Thanks for reply.
