### ISSUE TITLE
message

### ISSUE THREAD

**Issue by BelongsH** [drakeet/MultiType#7]
thanks you library.

When I met a different view of an entity when , how can I do ?

**Comment by drakeet** [comment]
entity when?

**Comment by drakeet** [comment]
Maybe you mean notifyDataChanged?

**Comment by drakeet** [comment]
The `TypeItemsAdapter` is a subclass of `RecyclerView.Adapter` so that you could hold the adapter and change the entity then call `adapter.notifyDataChanged` or  `adapter.notifyItemChanged(int position)` to update your view's UI state

https://github.com/drakeet/MultiType/blob/master/sample/src/main/java/me/drakeet/multitype/sample/page/MainActivity.java#L64

**Comment by drakeet** [comment]
If an entity on its initial process has multiple UI performances or layouts, you could use `if` in `onBindView` of `ItemViewProvider` and react different UI, such as `setBackground`.

**Comment by BelongsH** [comment]
thanks.

I think if use if or switch  in onBindView of ItemViewProvider , and before the writing is no different.
